In [2]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

In [4]:
iris=load_iris()

In [5]:
X=iris.data
y=iris.target

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
X_train.shape

(120, 4)

In [11]:
X_test.shape

(30, 4)

In [10]:
y_train.shape

(120,)

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lr=LinearRegression()

In [14]:
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
y_pred=lr.predict(X_test)

In [16]:
y_pred

array([ 1.23071715, -0.04010441,  2.21970287,  1.34966889,  1.28429336,
        0.02248402,  1.05726124,  1.82403704,  1.36824643,  1.06766437,
        1.70031437, -0.07357413, -0.15562919, -0.06569402, -0.02128628,
        1.39659966,  2.00022876,  1.04812731,  1.28102792,  1.97283506,
        0.03184612,  1.59830192,  0.09450931,  1.91807547,  1.83296682,
        1.87877315,  1.78781234,  2.03362373,  0.03594506,  0.02619043])

In [28]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [29]:
print("MSE :",mean_squared_error(y_test,y_pred))
print("MAE :",mean_absolute_error(y_test,y_pred))
print("RMSE :",root_mean_squared_error(y_test,y_pred))
print("R2 Score :",r2_score(y_test,y_pred))

MSE : 0.03711379440797688
MAE : 0.1463769496530853
RMSE : 0.1926494080135646
R2 Score : 0.9468960016420045


In [30]:
lr.coef_

array([-0.11633479, -0.05977785,  0.25491375,  0.54759598])

In [31]:
lr.intercept_

np.float64(0.2525275898181455)

# Making Own Linear Regression

In [32]:
class MyLinearReg:
    def __init__(self):
        self.coef_=None
        self.intercept_=None

    def fit(self,X_train,y_train):
        X_train=np.insert(X_train,0,1,axis=1)

        # calculate the coeffs
        betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_=betas[0]
        self.coef_=betas[1:]
    def predict(self,X_test):
        y_pred=np.dot(X_test,self.coef_)+self.intercept_
        return y_pred

In [33]:
le=MyLinearReg()


In [34]:
le.fit(X_train,y_train)

In [35]:
y_pred_le=le.predict(X_test)

In [36]:
r2_score(y_test,y_pred)

0.9468960016420045

In [37]:
le.coef_

array([-0.11633479, -0.05977785,  0.25491375,  0.54759598])

In [38]:
le.intercept_

np.float64(0.2525275898178583)